feat: made advanced settings for token creation read-only
yral-dapp/hot-or-not-web-leptos-ssr pull request #534
Opened 2024-11-25 14:55 UTC by tushar-saxena-yral

Closes #529

Disables the fields, but the ux is a bit compromised. Should I add a bit styling and a white text saying something along the lines of `you can't change these settings`? or is this good enough

2024-11-25 16:41 UTC, rupansh-sekar-yral commented
@saikatdas0790 thoughts on UX suggestions?

2024-11-26 00:56 UTC, saikatdas0790 commented
@tushar-saxena-yral Let's bring this up during today's meeting?

2024-11-27 06:55 UTC, rupansh-sekar-yral submitted a review, later dismissed

2024-12-12 15:03 UTC, tushar-saxena-yral commented
https://www.figma.com/file/qly4tjTKMMbdOO4IrLzOeC?node-id=766:2199&locale=en&type=design
- [x] Create the banner
- [x] Implement the settings card
- [ ] Add tooltips with description

2024-12-13 05:34 UTC, tushar-saxena-yral commented
@harshita-srivastava-yral i cut some corners with the tooltip to save dev time. lemme know if you want it to be pixel perfect, otherwise i feel it will suffice

2025-01-02 17:30 UTC, rupansh-sekar-yral approved these changes

2025-01-02 17:37 UTC, tushar-saxena-yral commented
@ravi-sawlani-yral hey i merged main and the e2e test (walletTest) seems to be failing, but if i understand this correctly i haven't changed anything related to wallet

2025-01-03 08:49 UTC, ravi-sawlani-yral requested changes
We should add a e2e test to verify this usecase.

2025-02-03 08:57 UTC, ravi-sawlani-yral commented
@tushar-saxena-yral is this PR ready?

2025-02-06 18:21 UTC, tushar-saxena-yral commented
> @tushar-saxena-yral is this PR ready?

the pr itself is ready, but some unrelated tests are failing. i need to look into why exactly

2025-02-07 05:38 UTC, ravi-sawlani-yral commented
> > @tushar-saxena-yral is this PR ready?
> 
> the pr itself is ready, but some unrelated tests are failing. i need to look into why exactly

Tests are passing but we would a e2e test for this change.

2025-02-11 07:08 UTC, tushar-saxena-yral commented
@ravi-sawlani-yral im assuming you mean to test that the fields are _indeed_ read-only. but they are just `div`s now. other than that, what else can i write a test for?

2025-02-12 05:56 UTC, ravi-sawlani-yral commented
> @ravi-sawlani-yral im assuming you mean to test that the fields are _indeed_ read-only. but they are just `div`s now. other than that, what else can i write a test for?

Write a test that checks the fields are disabled

2025-02-19 04:30 UTC, ravi-sawlani-yral requested changes

2025-02-19 04:30 UTC, ravi-sawlani-yral commented on tests/e2e/src/tokenCreationTest.js
> +        browser.pause(5000); // let the browser load the page
We should not prefer explicit waits. Maybe we use this to wait for element https://nightwatchjs.org/api/waitForElementVisible.html#waitForElementVisible

2025-02-19 04:30 UTC, ravi-sawlani-yral commented on tests/e2e/src/tokenCreationTest.js
> +    })
We should assert on css property of the divs. Try using this example: https://nightwatchjs.org/api/expect/#expect-matchers

2025-02-25 11:15 UTC, ravi-sawlani-yral approved these changes

2025-02-25 11:16 UTC, merged