Add airdrop page
yral-dapp/hot-or-not-web-leptos-ssr pull request #552
Opened 2024-12-09 09:48 UTC by harsh-mn-yral

closes  #515

2024-12-09 09:56 UTC, joel-medicala-yral commented
can we target this later? because i'm not quite sure how the wallet has to be integrated with this... So just make a PR for the wallet we'll come to this later

2025-01-02 07:22 UTC, harshita-srivastava-yral commented
@joel-medicala-yral This is good to go! Please assign it to reviewer and help merging it in main

2025-01-02 10:16 UTC, rupansh-sekar-yral requested changes
Mostly code style issues, looks good other wise!
Feel free to skip on them if you think it doesn't make sense to divide the component(s)

2025-01-02 10:16 UTC, rupansh-sekar-yral commented on ssr/src/page/profile/tokens.rs
> +            let cans = Canisters::from_wire(auth_cans_wire?, expect_context())?;
rightward drift is a bit too much in this function, can we break it down into smaller pieces?

2025-01-02 10:16 UTC, rupansh-sekar-yral commented on ssr/src/page/wallet/tokens.rs
> +pub fn WalletCard(
this component has become really long, makes sense to break it down?

2025-01-02 10:16 UTC, rupansh-sekar-yral commented on ssr/src/page/wallet/airdrop.rs
> +pub fn AirdropPage(meta: TokenMetadata, airdrop_amount: u64) -> impl IntoView {
This component is really large, break it down?

2025-01-02 11:21 UTC, joel-medicala-yral commented on ssr/src/page/wallet/tokens.rs
> +pub fn WalletCard(
I could separate out the Buttons but the problem is that it would make the args of the Button Component massive due to the sheer number of signals and all its using, would be better to keep them together to maintain redability... Thoughts @rupansh-sekar-yral ?

2025-01-02 16:32 UTC, rupansh-sekar-yral commented on ssr/src/page/wallet/tokens.rs
> +pub fn WalletCard(
you can use a context in that case

2025-01-03 04:41 UTC, rupansh-sekar-yral approved these changes

2025-01-03 04:43 UTC, merged